//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.29 at 09:57:13 PM YEKT 
//


package ru.csu.stan.java.classgen.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BaseTypedElement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BaseTypedElement">
 *   &lt;complexContent>
 *     &lt;extension base="{}BaseElement">
 *       &lt;sequence>
 *         &lt;element name="CommonType" type="{}CommonType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="AggregatedType" type="{}AggregatedType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BaseTypedElement", propOrder = {
    "commonType",
    "aggregatedType"
})
@XmlSeeAlso({
    Argument.class,
    Method.class,
    Attribute.class
})
public class BaseTypedElement
    extends BaseElement
{

    @XmlElement(name = "CommonType")
    protected List<CommonType> commonType;
    @XmlElement(name = "AggregatedType")
    protected List<AggregatedType> aggregatedType;

    /**
     * Gets the value of the commonType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the commonType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCommonType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CommonType }
     * 
     * 
     */
    public List<CommonType> getCommonType() {
        if (commonType == null) {
            commonType = new ArrayList<CommonType>();
        }
        return this.commonType;
    }

    /**
     * Gets the value of the aggregatedType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the aggregatedType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAggregatedType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AggregatedType }
     * 
     * 
     */
    public List<AggregatedType> getAggregatedType() {
        if (aggregatedType == null) {
            aggregatedType = new ArrayList<AggregatedType>();
        }
        return this.aggregatedType;
    }

}
