//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.27 at 10:05:31 PM YEKT 
//


package ru.csu.stan.java.cfg.jaxb;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Call complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Call">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice minOccurs="0">
 *         &lt;element name="Direct" type="{}Direct"/>
 *         &lt;element name="Getattr" type="{}Getattr"/>
 *       &lt;/choice>
 *       &lt;attribute name="fromlineno" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="col_offset" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Call", propOrder = {
    "direct",
    "getattr"
})
public class Call {

    @XmlElement(name = "Direct")
    protected Direct direct;
    @XmlElement(name = "Getattr")
    protected Getattr getattr;
    @XmlAttribute
    protected BigInteger fromlineno;
    @XmlAttribute(name = "col_offset")
    protected BigInteger colOffset;

    /**
     * Gets the value of the direct property.
     * 
     * @return
     *     possible object is
     *     {@link Direct }
     *     
     */
    public Direct getDirect() {
        return direct;
    }

    /**
     * Sets the value of the direct property.
     * 
     * @param value
     *     allowed object is
     *     {@link Direct }
     *     
     */
    public void setDirect(Direct value) {
        this.direct = value;
    }

    /**
     * Gets the value of the getattr property.
     * 
     * @return
     *     possible object is
     *     {@link Getattr }
     *     
     */
    public Getattr getGetattr() {
        return getattr;
    }

    /**
     * Sets the value of the getattr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Getattr }
     *     
     */
    public void setGetattr(Getattr value) {
        this.getattr = value;
    }

    /**
     * Gets the value of the fromlineno property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFromlineno() {
        return fromlineno;
    }

    /**
     * Sets the value of the fromlineno property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFromlineno(BigInteger value) {
        this.fromlineno = value;
    }

    /**
     * Gets the value of the colOffset property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getColOffset() {
        return colOffset;
    }

    /**
     * Sets the value of the colOffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setColOffset(BigInteger value) {
        this.colOffset = value;
    }

}
