//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.01 at 07:24:41 PM YEKT 
//


package ru.csu.stan.java.cfg.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Direct complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Direct">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice minOccurs="0">
 *         &lt;element name="TargetClass" type="{}TargetClass"/>
 *         &lt;element name="TargetFunction" type="{}TargetFunction"/>
 *         &lt;element name="TargetUnknown" type="{}TargetUnknown"/>
 *       &lt;/choice>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="space_type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Direct", propOrder = {
    "targetClass",
    "targetFunction",
    "targetUnknown"
})
public class Direct {

    @XmlElement(name = "TargetClass")
    protected TargetClass targetClass;
    @XmlElement(name = "TargetFunction")
    protected TargetFunction targetFunction;
    @XmlElement(name = "TargetUnknown")
    protected TargetUnknown targetUnknown;
    @XmlAttribute
    protected String name;
    @XmlAttribute(name = "space_type")
    protected String spaceType;

    /**
     * Gets the value of the targetClass property.
     * 
     * @return
     *     possible object is
     *     {@link TargetClass }
     *     
     */
    public TargetClass getTargetClass() {
        return targetClass;
    }

    /**
     * Sets the value of the targetClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link TargetClass }
     *     
     */
    public void setTargetClass(TargetClass value) {
        this.targetClass = value;
    }

    /**
     * Gets the value of the targetFunction property.
     * 
     * @return
     *     possible object is
     *     {@link TargetFunction }
     *     
     */
    public TargetFunction getTargetFunction() {
        return targetFunction;
    }

    /**
     * Sets the value of the targetFunction property.
     * 
     * @param value
     *     allowed object is
     *     {@link TargetFunction }
     *     
     */
    public void setTargetFunction(TargetFunction value) {
        this.targetFunction = value;
    }

    /**
     * Gets the value of the targetUnknown property.
     * 
     * @return
     *     possible object is
     *     {@link TargetUnknown }
     *     
     */
    public TargetUnknown getTargetUnknown() {
        return targetUnknown;
    }

    /**
     * Sets the value of the targetUnknown property.
     * 
     * @param value
     *     allowed object is
     *     {@link TargetUnknown }
     *     
     */
    public void setTargetUnknown(TargetUnknown value) {
        this.targetUnknown = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the spaceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpaceType() {
        return spaceType;
    }

    /**
     * Sets the value of the spaceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpaceType(String value) {
        this.spaceType = value;
    }

}
