//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.01 at 02:16:27 PM YEKT 
//


package ru.csu.stan.java.cfg.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for For complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="For">
 *   &lt;complexContent>
 *     &lt;extension base="{}BaseCfgElement">
 *       &lt;attribute name="iterate" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "For")
public class For
    extends BaseCfgElement
{

    @XmlAttribute
    protected String iterate;

    /**
     * Gets the value of the iterate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIterate() {
        return iterate;
    }

    /**
     * Sets the value of the iterate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIterate(String value) {
        this.iterate = value;
    }

}
